# Generated by Django 3.2.8 on 2021-11-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='info',
        ),
    ]
